Algoritmo "NUMERO DE 1 A 50"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa 
// Descrição   : Desenvolver um programa que exiba do numero 1 ate o 50.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/09/2022
Var
// Seção de Declarações das variáveis
contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
enquanto contador < 50 faca
contador <- contador + 1
escreval(contador)
fimenquanto

Fimalgoritmo